production:
  adapter: mysql2
  encoding: utf8
  database: store
  username: root
  password: 24xhub
  timeout: 5000

development:
  adapter: mysql2
  encoding: utf8
  database: store
  username: root
  password: 24xhub
  timeout: 5000

test:
  adapter: mysql2
  encoding: utf8
  database: store-test
  username: root
  password: 24xhub
  timeout: 5000
